### ISSUE TITLE
Get the number of unique listeners per episode in specific date ranges

### ISSUE THREAD

**Issue by adrianmedinasocial** [openpodcast/spotify-connector#15]
Hi,

I'm working on a project where I need to get the number of unique listeners per episode in specific date ranges

I used connector.listeners(start, end, episode) to get the daily listeners per episode.
When I add up the daily counts to get a total by date range, the results don't match what's shown in the Spotify dashboard.
I suspect this is because adding up the daily listeners is counting the same listeners who listened on different days multiple times.
Trying connector.performance()

I tried using connector.performance(start, end, episode), but I got an error saying that the method doesn't accept start and end parameters: SpotifyConnector.performance() got an unexpected keyword argument 'start'.
My goal is to get the number of unique listeners per episode in specific date ranges, as shown in the Spotify for Podcasters dashboard.

Is there a way to get the number of unique listeners per episode and per date range using the Spotify API or the SpotifyConnector library?
If so, could you please provide me with guidance on which method to use and how to implement it correctly?

**Comment by adrianmedinasocial** [comment]
It is important to note that Star and Streamers are being recovered correctly by date range.

**Comment by mre** [comment]
Hey Adrian,

`performance` only takes an episode ID and returns a dictionary of performance data.

```python
# Get the performance of an episode
performance = connector.performance("episode_id")
```

The return value is the histogram of listener data for a given episode

 

```json
{
   "samples":[
      52,
      52,
      51,
      48,
      ...
      15,
      15
   ],
   "sampleRate":1000,
   "max":52,
   "seconds":4669,
   "percentiles":{
      "50":42,
      "100":29,
      "25":60,
      "75":33
   },
   "medianCompletion":{
      "percentage":34,
      "seconds":1601
   }
}
```

That's the data you see in the dashboard for a single episode, e.g.

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/519a54ed-9fc3-4bef-bb1c-e57ac5af6418">


So it doesn't solve your problem.

As you already discovered, the `listeners` endpoint gives you the number of unique listeners per day, but there could be an overlap (e.g. if someone continues listening on the next day or listens to an episode twice or on different devices). It's not accurate for what you need.

Here is the response for that endpoint:

```json
{"counts":[{"count":0,"date":"2024-11-14"},{"count":0,"date":"2024-11-15"},{"count":0,"date":"2024-11-16"},{"count":0,"date":"2024-11-17"},{"count":0,"date":"2024-11-18"},{"count":54,"date":"2024-11-19"},{"count":34,"date":"2024-11-20"}]}
```

I am not aware of any Spotify API that provides unique listeners; it might be something that Spotify just doesn't expose (both, in their external and internal APIs).

**Comment by adrianmedinasocial** [comment]
Hi @mre 

Any methods you recommend to obtain a rough estimate by date range, without overestimating the result?

**Comment by mre** [comment]
How far off are your aggregated numbers from the total you see on Spotify? This should give you a decent estimate of repeated listeners per day. 

So like if you have 100 total for 10 days and if you sum up each day and end up with 120, you know that 20% are repeated listeners. Then you can deduct that from the daily values. Might work just fine. From experience, there aren't that many repeats. 

Maybe @woolfg has a better idea.

**Comment by woolfg** [comment]
there is a way to fetch "unique listeners per episode in specific date range" from Spotify but we haven't implemented this API yet. @adrianmedinasocial is it an option for you to develop it with our help/guidance and contribute it to the project?

**Comment by mre** [comment]
Relevant issue: https://github.com/openpodcast/api/issues/134

**Comment by mre** [comment]
The `episodes` endpoint calculates the unique listeners for the specified date range.

@adrianmedinasocial, can you try to use the `episodes` endpoint instead of the `listeners` endpoint and see if you get the unique values per day from the API if you iterate over your date range by day?

you can try that with a simple for-loop:

```python
start = dt.date(2024, 10, 1)  
end = dt.date(2024, 10, 31)

for date in (start + dt.timedelta(days=i) for i in range((end - start).days + 1)):
    # The episodes() method returns an iterator. 
    # Since we only need one day's data at a time, we call `next()` to get the first result.
    daily_data = next(spotify.episodes(start=date, end=date))
    print(f"{date}: {daily_data.get('uniqueListeners', 0)} listeners")
    sleep(1)  # Rate limiting

```

**Comment by adrianmedinasocial** [comment]
Hi @mre 

Great, thanks for your reply, I managed to get the correct values, as displayed in the spotify dashboard

The problem was that when using connector.listeners() and adding the daily 'count', the script was adding the total number of streamers and not the number of unique listeners.

By changing the endpoint from connector.listeners() to connector.episodes() and accessing the 'listeners' field directly, you get the real number of unique listeners

The previous code was

`listeners_count = sum(item.get('count', 0) for item in listeners_data.get('counts', []))
`
The change that solved the problem is:

`unique_listeners = daily_data.get('listeners', 0)
`
since I'm getting the data in blocks of 7, it's now avoiding repeating counts

before:
`date_ranges = generate_weekly_date_ranges(release_date, today_date)

after
`date_ranges = generate_weekly_date_ranges(start_date, end_date, block_size=7)
`

PD:
I tried to access uniqueListeners, but it is not a valid field in the Spotify API

**Comment by mre** [comment]
Glad you figured it out!

**Comment by adrianmedinasocial** [comment]
The project I am developing is extensive, I will surely need to clarify other doubts; I can also contribute to the project.

Thank you.
