### ISSUE TITLE
Add impressions to spotify+anchor connector

### ISSUE THREAD

**Issue by woolfg** [openpodcast/spotify-connector#8]
`https://generic.wg.spotify.com/podcasters/v0/shows/0tJRC0UsObPCWLmmzmOkIs/impressions/daily?start=2023-09-10&end=2023-10-09`

- [x] Test possible params (spotify+anchor)
- [x] Document api in internal docs (spotify+anchor)
- [x] Add function to fetch impressions to connector (spotify+anchor)

![Image](https://github.com/openpodcast/spotify-connector/assets/1328269/aca275da-7f81-4343-8ba3-28b1d7b85b77)

**Comment by mre** [comment]
Documentation done.
Implementations:

- Spotify: https://github.com/openpodcast/spotify-connector/pull/10
- Anchor: https://github.com/openpodcast/anchor-connector/pull/5
